### ISSUE TITLE
Installer fails when Beat Saber is installed on a network drive

### ISSUE THREAD

**Issue by texel-sensei** [Umbranoxio/BeatSaberModInstaller#10]
I have installed Beat Saber on a network drive. When starting the installer it says it can't locate Beat Saber and I should point it to my installation.

In the following explorer menu no network drives are visible though.

**Comment by pcnorden** [comment]
Hey-o, this one is something that I found out the cause of from /r/sysadmin on reddit, and that is since the network share is mounted for the current user, it doesn't show up for elevated programs resulting in non-visible network share.

How to fix it? I don't have the slightest idea as everybody in the thread I read was fighting with eachother.

Just wanted to add why it doesn't show up, so that somebody hopefully can fix that. Take care =)

**Comment by texel-sensei** [comment]
Yes, the problem was caused by windows not mounting the network share as administrator. Thanks for the tip.

To fix it, I used
```
net use x: \\server\share
```
in an elevated command prompt. After that the installation worked.
