### ISSUE TITLE
Random large black head in the middle of external screen

### ISSUE THREAD

**Issue by awiklendt** [Umbranoxio/BeatSaberModInstaller#42]
When playing with mods installed, the in-headset experience is awesome but the viewers watching the external monitor/projector see a large hooded head in the middle of the screen blocking most of the active parts of the screen.

The https://modsaber.ml page has close to zero detail on what each mod does. Would be nice to be able to uninstall mods.

**Comment by megalon** [comment]
This is due to the default avatar clipping into the camera and becoming visible.
You can change avatars with Page UP / Page DOWN.

You can right click on mods in the mod installer to view more information about them.

Please join the discord server if you have more questions.
https://discord.gg/beatsabermods
