### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by marcelwirtz** [Umbranoxio/BeatSaberModInstaller#48]
If i try to start the ModInstaller i get the following with version 2.1.2:

![screenshot_1](https://user-images.githubusercontent.com/5042008/44618169-2a584980-a871-11e8-8030-e75752eca8d1.png)

With an older version i get the same error at start but i can see the main window.

If i select the game path in the older version i get:

```
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei BeatSaberModManager.FormMain.buttonFolderBrowser_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by fbereyziat** [comment]
Had this, but it appeared that my external drive on which beat saber (steam version) is installed was not recognized by window. I had to plug in in another usb port, and after it was recognized by windows, the mod installer ran fine.

**Comment by megalon** [comment]
This is caused by having the game installed in a different directory than the default Oculus directory.
I helped someone though this exact problem yesterday on the Discord server.
The solution was to move the game to the folder
`H:\Oculus\Software\Software\hyperbolic-magnetism-beat-saber`
And set `H:\Oculus\Software\Software` as the default install directory for the Oculus installer.
