### ISSUE TITLE
Does not load in game

### ISSUE THREAD

**Issue by MrGun101** [Umbranoxio/BeatSaberModInstaller#49]
I was able to install the mod but it does not show up on Beat Saber itself. Please send a full step-by-step walkthrough on how to properly install.

**Comment by megalon** [comment]
There are a couple of possibilities here.

1. After the game updates, Beat Saber will automatically move the `Plugins` folder into the folder `IncompatiblePlugins` the next time you run the game. Beat Saber doesn't actually check if the plugins are out of date, it will do it no matter what. If you ran the installer before running the game for the first time, the game would have moved your new plugins into the `IncompatiblePlugins` folder. To fix this, just run the mod installer again. Beat Saber only does this the first time you launch it after an update. Next time the game updates, run the game once so that the `Plugins` folder is moved to `IncompatiblePlugins`, quit the game, then run the mod installer and launch the game again.

2. If your game is outdated, the mods will likely not work because they are all designed for the latest version of the game (currently version v0.11.2). Update your game to the current version and follow the steps above.
