### ISSUE TITLE
Error: Failed to get Version info! Please check your internet connection!

### ISSUE THREAD

**Issue by DanielDC88** [Umbranoxio/BeatSaberModInstaller#66]
https://i.imgur.com/5ssUeQs.png

Internet connection appears to be working fine when receiving this message.

**Comment by GeorgeGedox** [comment]
Why is this issue closed ? This is still a recurring problem.

Edit: Found out that the modsaber host is down so instead of the program trowing this error and closing, at least show a relevant error and check if the host is up and running or do a real internet connection check on the user's part such as sending a ping to google or to a DNS server.
